jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set Terraform Cloud Token
        run: echo "TFC_API_TOKEN=${{ secrets.TFC_API_TOKEN }}" >> $GITHUB_ENV
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
