name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch you want to trigger the pipeline on

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify your Terraform version here

      # Step 3: Set TF_LOG environment variable for debugging (optional)
      - name: Set TF_LOG environment variable for debugging
        run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      # Step 4: Set Terraform Cloud Token (if using Terraform Cloud, optional)
      - name: Set Terraform Cloud Token
        run: echo "TFE_TOKEN=${{ secrets.TFE_TOKEN }}" >> $GITHUB_ENV

      # Step 5: Set up Azure credentials
      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 6: Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Step 7: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -parallelism=10 -out=tfplan -input=false

      # Step 8: Apply the Terraform Plan (with auto-approve to bypass manual approval)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # Optional: Clean up after execution (if necessary)
      - name: Clean up
        run: terraform destroy -auto-approve
        if: ${{ always() }}  # This step runs even if the previous steps failed
